[package]
name = "migration"
version = "0.4.0"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
sea-orm-migration.workspace = true
tokio.workspace = true
