//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "activities")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub mode: Option<String>,
    pub min_fireteam_size: i32,
    pub max_fireteam_size: i32,
    pub min_light: Option<i32>,
    pub min_level: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::activityshortcuts::Entity")]
    Activityshortcuts,
    #[sea_orm(has_many = "super::plannedactivities::Entity")]
    Plannedactivities,
}

impl Related<super::activityshortcuts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Activityshortcuts.def()
    }
}

impl Related<super::plannedactivities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Plannedactivities.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
