//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "alerts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text", unique)]
    pub guid: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
    pub startdate: TimeDateTimeWithTimeZone,
    pub expirydate: Option<TimeDateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub faction: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub flavor: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
