//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "plannedactivities")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub author_id: i32,
    pub activity_id: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub details: Option<String>,
    pub start: TimeDateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::activities::Entity",
        from = "Column::ActivityId",
        to = "super::activities::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Activities,
    #[sea_orm(
        belongs_to = "super::guardians::Entity",
        from = "Column::AuthorId",
        to = "super::guardians::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Guardians,
    #[sea_orm(has_many = "super::plannedactivitymembers::Entity")]
    Plannedactivitymembers,
}

impl Related<super::activities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Activities.def()
    }
}

impl Related<super::guardians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Guardians.def()
    }
}

impl Related<super::plannedactivitymembers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Plannedactivitymembers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
