[package]
authors = ["Berkus Decker <berkus+cargo@metta.systems>"]
name = "aegl_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.4"
lazy_static = "1.4"
chrono = "0.4"
chrono-tz = "0.5"
chrono-english = "0.1"
diesel_derives_extra = "0.2"
diesel_derives_traits = "0.2"
diesel_logger = "0.1"
#diesel_migrations = "1.4.0" -- retry with "extern crate" macros
r2d2 = "0.8"
dotenv = "0.15"
anyhow = "1.0"
futures = "0.3" #fixme 0.1
serde_json = "1.0"
telebot = "0.3"
log = "0.4"
fern = { version = "0.6", features = ["colored"] }
futures-retry = "0.6"
itertools = "0.10"
# plurals = "0.3"
tokio = { version =  "1.5", features = ["macros", "rt-multi-thread"] }
#tokio = "0.1.20"
#tokio-core = "0.1.17"

[dependencies.diesel]
features = [
    "postgres",
    "chrono",
    "serde_json",
    "r2d2",
]
version = "1.4"

[target.'cfg(target_os="linux")'.dependencies]
procfs = "0.9"
