[package]
authors = ["Berkus Decker <berkus+cargo@metta.systems>"]
name = "aegl_bot"
version = "0.1.0"

[dependencies]
dotenv = "0.11.0"

[dependencies.diesel]
features = ["postgres"]
version = "1.2.2"
