[package]
authors = ["Berkus Decker <berkus+cargo@metta.systems>"]
name = "aegl_bot"
version = "0.1.0"

[dependencies]
chrono = "0.4.2"
chrono-tz = "0.5.0"
chrono-english = "0.1.2"
diesel_derives_extra = "0.1.2"
diesel_derives_traits = "0.1.2"
# diesel-derive-more = "1.1.3"
r2d2 = "0.8.2"
dotenv = "0.11.0"
failure = "0.1.1"
futures = "0.1.23"
serde_json = "1.0.17"
telebot = "^0.2.9"
tokio = "0.1.8"
tokio-core = "0.1.17"
log = "0.4"
pretty_env_logger = "0.2"

[dependencies.diesel]
features = [
    "postgres",
    "chrono",
    "serde_json",
    "r2d2",
]
version = "1.3.2"

[dependencies.rss]
features = ["from_url"]
version = "1.5.0"
