[package]
authors = ["Berkus Decker <berkus+cargo@metta.systems>"]
name = "aegl_bot"
version = "0.1.0"

[dependencies]
regex = "1"
lazy_static = "1.1.0"
chrono = "0.4.6"
chrono-tz = "0.5.0"
chrono-english = "0.1.2"
diesel_derives_extra = "0.1.2"
diesel_derives_traits = "0.1.2"
# diesel-derive-more = "1.1.3"
diesel_logger = "0.1.0"
r2d2 = "0.8.2"
dotenv = "0.13.0"
failure = "0.1.2"
futures = "0.1.24"
serde_json = "1.0.26"
telebot = "0.2.9"
tokio = "0.1.8"
tokio-core = "0.1.17"
log = "0.4.5"
fern = { version = "0.5.6", features = ["colored"] }
futures-retry = "0.2.1"
itertools = "0.7.8"

[dependencies.diesel]
features = [
    "postgres",
    "chrono",
    "serde_json",
    "r2d2",
]
version = "1.3.2"

[dependencies.rss]
features = ["from_url"]
version = "1.5.0"

[target.'cfg(target_os="linux")'.dependencies]
procfs = "0.4.7"
