[package]
authors = ["Berkus Decker <berkus+cargo@metta.systems>"]
name = "aegl_bot"
version = "0.1.0"

[dependencies]
chrono = "0.4.2"
dotenv = "0.11.0"
futures = "0.1.1"
serde_json = "1.0.17"
telegram-bot = "0.6.1"
tokio-core = "0.1.17"

[dependencies.diesel]
features = [
    "postgres",
    "chrono",
    "serde_json",
]
version = "1.2.2"

[dependencies.rss]
features = ["from_url"]
version = "1.5.0"
