//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1
//-------------------------------------------------------------------------------------------------
// Activity
//-------------------------------------------------------------------------------------------------

use sea_orm::entity::prelude::*;

// Old diesel schema for reference:
// table! {
//     activities (id) {
//         id -> Int4,
//         name -> Text,
//         mode -> Nullable<Text>,
//         min_fireteam_size -> Int4,
//         max_fireteam_size -> Int4,
//         min_light -> Nullable<Int4>,
//         min_level -> Nullable<Int4>,
//     }
// }

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "activities")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub mode: Option<String>,
    pub min_fireteam_size: i32,
    pub max_fireteam_size: i32,
    pub min_light: Option<i32>,
    pub min_level: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::activityshortcuts::Entity")]
    Activityshortcuts,
    #[sea_orm(has_many = "super::plannedactivities::Entity")]
    Plannedactivities,
}

impl Related<super::activityshortcuts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Activityshortcuts.def()
    }
}

impl Related<super::plannedactivities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Plannedactivities.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl Model {
    pub fn format_name(&self) -> String {
        format!("{} {}", self.name, self.mode.clone().unwrap_or_default())
    }
}

#[cfg(test)]
mod tests {
    use {super::*, crate::establish_db_connection, diesel::prelude::*};

    #[test]
    #[ignore]
    fn test_activities() -> Result<(), r2d2::Error> {
        use crate::schema::activities::dsl::*;

        dotenv::dotenv().ok();
        let pool = establish_db_connection();
        let connection = pool.get()?;

        let results = activities
            .load::<Activity>(&connection)
            .expect("Error loading activities");

        println!("Displaying {} activities", results.len());
        for act in results {
            println!("{}", act.format_name());
        }

        Ok(())
    }
}
