//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "guardians")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text", unique)]
    pub telegram_name: String,
    #[sea_orm(unique)]
    pub telegram_id: i64,
    #[sea_orm(column_type = "Text")]
    pub psn_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub email: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub psn_clan: Option<String>,
    pub created_at: TimeDateTimeWithTimeZone,
    pub updated_at: TimeDateTimeWithTimeZone,
    pub deleted_at: Option<TimeDateTimeWithTimeZone>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub tokens: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub pending_activation_code: Option<String>,
    pub is_admin: bool,
    pub is_superadmin: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::plannedactivities::Entity")]
    Plannedactivities,
    #[sea_orm(has_many = "super::plannedactivitymembers::Entity")]
    Plannedactivitymembers,
}

impl Related<super::plannedactivities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Plannedactivities.def()
    }
}

impl Related<super::plannedactivitymembers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Plannedactivitymembers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
