//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "plannedactivitymembers")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub planned_activity_id: i32,
    pub user_id: i32,
    pub added: TimeDateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::guardians::Entity",
        from = "Column::UserId",
        to = "super::guardians::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Guardians,
    #[sea_orm(
        belongs_to = "super::plannedactivities::Entity",
        from = "Column::PlannedActivityId",
        to = "super::plannedactivities::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Plannedactivities,
}

impl Related<super::guardians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Guardians.def()
    }
}

impl Related<super::plannedactivities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Plannedactivities.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
