//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1
//-------------------------------------------------------------------------------------------------
// PlannedActivity
//-------------------------------------------------------------------------------------------------

use sea_orm::entity::prelude::*;

// Old diesel schema for reference:
// table! {
//     plannedactivities (id) {
//         id -> Int4,
//         author_id -> Int4,
//         activity_id -> Int4,
//         details -> Nullable<Text>,
//         start -> Timestamptz,
//     }
// }

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "plannedactivities")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub author_id: i32,   // refs Guardians
    pub activity_id: i32, // refs Activities
    #[sea_orm(column_type = "Text", nullable)]
    pub details: Option<String>,
    pub start: TimeDateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::activities::Entity",
        from = "Column::ActivityId",
        to = "super::activities::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Activities,
    #[sea_orm(
        belongs_to = "super::guardians::Entity",
        from = "Column::AuthorId",
        to = "super::guardians::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Guardians,
    #[sea_orm(has_many = "super::plannedactivitymembers::Entity")]
    Plannedactivitymembers,
}

impl Related<super::activities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Activities.def()
    }
}

impl Related<super::guardians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Guardians.def()
    }
}

impl Related<super::plannedactivitymembers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Plannedactivitymembers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

// Old diesel model for reference:
/*

// todo: tera templates in own crate? have a ToTemplate kinda trait?

// Output information
#[derive(Serialize, Deserialize)]
pub struct PlannedActivityTemplate {
    pub id: i32,
    pub name: String,
    pub details: String,
    pub members: Vec<ActivityMemberTemplate>,
    pub count: usize,
    pub time: String,
    pub fireteam_full: bool,
    pub fireteam_joined: bool,
    pub join_link: String,
    pub leave_link: String,
}
*/
impl Model {
    pub fn to_template(
        &self,
        guardian: Option<&Guardian>,
        connection: &DbConnection,
    ) -> PlannedActivityTemplate {
        let activity = self.activity(connection);

        let count = activity.max_fireteam_size as usize - self.members_count(connection);

        PlannedActivityTemplate {
            id: self.id,
            name: activity.format_name(),
            details: self.format_details(),
            members: self
                .members(connection)
                .into_iter()
                .map(|m| m.to_template(connection))
                .collect(),
            count,
            time: format_start_time(self.start, reference_date()),
            fireteam_full: count == 0,
            join_link: self.join_prompt(connection),
            fireteam_joined: self.find_member(connection, guardian).is_some(),
            leave_link: self.cancel_link(),
        }
    }

    // @fixme: that should be on Entity?
    pub async fn upcoming_activities(connection: &DbConnection) -> Vec<PlannedActivity> {
        use crate::{datetime::nowtz, schema::plannedactivities::dsl::*};

        plannedactivities::Entity::find()
            .cursor_by(PlannedActivity::Column::Start)
            .after(nowtz() - 60_i32.minutes())
            .all(&connection)
            .await?
    }

    pub fn author(&self, connection: &DbConnection) -> Option<Guardian> {
        Guardian::find_one(connection, &self.author_id)
            .expect("Failed to load PlannedActivity author")
    }

    pub fn activity(&self, connection: &DbConnection) -> Activity {
        Activity::find_one(connection, &self.activity_id)
            .expect("Failed to load associated Activity")
            .expect("PlannedActivity without Activity shouldn't exist")
    }

    pub fn members(&self, connection: &DbConnection) -> Vec<PlannedActivityMember> {
        use crate::schema::plannedactivitymembers::dsl::*;
        plannedactivitymembers
            .filter(planned_activity_id.eq(self.id))
            .order(added.asc())
            .load::<PlannedActivityMember>(connection)
            .expect("Failed to load PlannedActivity members")
    }

    pub fn members_count(&self, connection: &DbConnection) -> usize {
        //@TODO replace with proper diesel query
        self.members(connection).len()
    }

    pub fn join_link(&self) -> String {
        format!("/join{}", self.id)
    }

    pub fn cancel_link(&self) -> String {
        format!("/cancel{}", self.id)
    }

    pub fn join_prompt(&self, connection: &DbConnection) -> String {
        if self.is_full(connection) {
            "This activity fireteam is full.".into()
        } else {
            let count = self.activity(connection).max_fireteam_size as usize
                - self.members_count(connection);
            format!(
                "Enter `{joinLink}` to join this group. Up to {count} more can join.",
                joinLink = self.join_link(),
                count = count
            )
        }
    }

    pub fn is_full(&self, connection: &DbConnection) -> bool {
        self.members(connection).len() >= self.activity(connection).max_fireteam_size as usize
    }

    pub fn requires_more_members(&self, connection: &DbConnection) -> bool {
        self.members(connection).len() < self.activity(connection).min_fireteam_size as usize
    }

    pub fn format_details(&self) -> String {
        self.details.clone().map(|s| s + "\n").unwrap_or_default()
    }

    pub fn members_formatted(&self, connection: &DbConnection, joiner: &str) -> String {
        self.members(connection)
            .into_iter()
            .map(|guardian| guardian.format_name(connection))
            .collect::<Vec<String>>()
            .as_slice()
            .join(joiner)
    }

    pub fn members_formatted_list(&self, connection: &DbConnection) -> String {
        self.members_formatted(connection, ", ")
    }

    pub fn members_formatted_column(&self, connection: &DbConnection) -> String {
        self.members_formatted(connection, "\n")
    }

    // This should be on Entity?
    pub fn find_member(
        &self,
        connection: &DbConnection,
        guardian: Option<&Guardian>,
    ) -> Option<PlannedActivityMember> {
        use crate::schema::plannedactivitymembers::dsl::*;

        guardian.and_then(|g| {
            plannedactivitymembers
                .filter(user_id.eq(g.id))
                .filter(planned_activity_id.eq(self.id))
                .first::<PlannedActivityMember>(connection)
                .optional()
                .expect("Failed to run SQL")
        })
    }

    // Makes a telegram Html formatted display.
    pub fn to_string(&self, connection: &DbConnection, g: Option<&Guardian>) -> String {
        let event = self.to_template(g, connection);
        render_template!("list/event", ("event", &event))
            .expect("Failed to render list event template")
    }
}

#[cfg(test)]
mod tests {
    use {super::*, crate::establish_db_connection, diesel::prelude::*};

    #[test]
    #[ignore]
    fn test_planned_activities() -> Result<(), r2d2::Error> {
        use crate::schema::guardians::dsl::*;

        dotenv::dotenv().ok();
        let pool = establish_db_connection();
        let connection = pool.get()?;

        let guar = guardians
            .find(1)
            .first::<Guardian>(&connection)
            .expect("Guardian with id 1 not found");
        let results = PlannedActivity::belonging_to(&guar)
            .load::<PlannedActivity>(&connection)
            .expect("Error loading activities");

        println!("Displaying {} planned activities", results.len());
        for act in results {
            println!("{}", act.to_string(&connection, Some(&guar)));
        }

        Ok(())
    }
}
