//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1
//-------------------------------------------------------------------------------------------------
// PlannedActivityMember
//-------------------------------------------------------------------------------------------------

use sea_orm::entity::prelude::*;

// Old diesel schema for reference:
// table! {
//     plannedactivitymembers (id) {
//         id -> Int4,
//         planned_activity_id -> Int4,
//         user_id -> Int4,
//         added -> Timestamptz,
//     }
// }

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "plannedactivitymembers")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub planned_activity_id: i32,
    pub user_id: i32,
    pub added: TimeDateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::guardians::Entity",
        from = "Column::UserId",
        to = "super::guardians::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Guardians,
    #[sea_orm(
        belongs_to = "super::plannedactivities::Entity",
        from = "Column::PlannedActivityId",
        to = "super::plannedactivities::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Plannedactivities,
}

impl Related<super::guardians::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Guardians.def()
    }
}

impl Related<super::plannedactivities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Plannedactivities.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

// todo Tera templates
#[derive(Serialize, Deserialize)]
pub struct ActivityMemberTemplate {
    pub psn_name: String,
    pub telegram_name: String,
    pub icon: String,
}

impl Model {
    pub fn format_name(&self, connection: &DbConnection) -> String {
        Guardian::find_one(connection, &self.user_id)
            .expect("Failed to load associated Guardian")
            .expect("Failed to find associated activity member")
            .format_name()
    }

    pub fn to_template(&self, connection: &DbConnection) -> ActivityMemberTemplate {
        let (telegram_name, psn_name) = Guardian::find_one(connection, &self.user_id)
            .expect("Failed to load associated Guardian")
            .expect("Failed to find associated activity member")
            .names();
        ActivityMemberTemplate {
            psn_name,
            telegram_name,
            icon: self.icon(),
        }
    }

    pub fn icon(&self) -> String {
        static ICON_POOL: LazyLock<Vec<&str>> = LazyLock::new(|| {
            vec![
                "💂🏻",
                "🕵🏼",
                "🧑🏽‍🏭",
                "🧑‍💻",
                "🧑🏼‍🚒",
                "🧑🏾‍🚀",
                "🥷🏾",
                "🥷🏻",
                "🧙🏽",
                "🧝🏼",
                "🧌",
                "🧛🏼",
                "🧟",
            ]
        });
        ICON_POOL[self.user_id.unsigned_abs() as usize % ICON_POOL.len()].into()
    }
}
