//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

pub use super::{
    activities::Entity as Activities, activityshortcuts::Entity as Activityshortcuts,
    alerts::Entity as Alerts, guardians::Entity as Guardians,
    plannedactivities::Entity as Plannedactivities,
    plannedactivitymembers::Entity as Plannedactivitymembers,
};
