//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

pub use super::{
    activities::Entity as Activities, activityshortcuts::Entity as ActivityShortcuts,
    alerts::Entity as Alerts, guardians::Entity as Guardians,
    plannedactivities::Entity as PlannedActivities,
    plannedactivitymembers::Entity as PlannedActivityMembers,
};
